### ISSUE TITLE
Problems while installing

### ISSUE THREAD

**Issue by iakanoe** [CFT-Chris/capacitor-pwa-firebase-msg#2]
Hi! I really need to use FCM ASAP on an Ionic PWA and I found your PR on the capacitor project so I'm trying to use this repo with the instructions you provided on README.md but I'm having problems when running `npm install capacitor-pwa-firebase-msg` (the way the repo states it has to be installed) or `npm install https://github.com/CFT-Chris/capacitor-pwa-firebase-msg` (another way I tried, directly from Github).

Console output:

```
C:\Users\Ianick\Proyectos\AusentismoPWA>npm i capacitor-pwa-firebase-msg >> out.txt
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/node-v83-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.23.3 and node@14.3.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.6.30114.105) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "Visual Studio C++ core features" missing
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ianick\\AppData\\Roaming\\nvm\\v14.3.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\Ianick\\Proyectos\\AusentismoPWA\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\Ianick\\Proyectos\\AusentismoPWA\\node_modules\\grpc\\src\\node\\extension_binary\\node-v83-win32-x64-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83" "--python=C:\\depot-tools\\bootstrap-3_8_0b1_chromium_1_bin\\python\\bin"
gyp ERR! cwd C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Ianick\AppData\Roaming\nvm\v14.3.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83 --python=C:\depot-tools\bootstrap-3_8_0b1_chromium_1_bin\python\bin' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Windows_NT 10.0.18362
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ianick\\Proyectos\\AusentismoPWA\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\Ianick\Proyectos\AusentismoPWA\node_modules\grpc
node-pre-gyp ERR! node -v v14.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\openvidu-browser\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.23.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ianick\AppData\Roaming\npm-cache\_logs\2020-06-03T20_53_42_970Z-debug.log
```

There seems to be a problem while installing grpc, that I have also found on the grpc repo on GH. I don't really know what is happening (I have not taken much time to debug) but I figured maybe you could help me fix it...

**Comment by CFT-Chris** [comment]
Unsure if this error is related at all to the project.  Looks like an NPM setup issue on your machine.

I just did a quick search.  Perhaps this might help you?  https://stackoverflow.com/questions/57879150/how-can-i-solve-error-gypgyp-errerr-find-vsfind-vs-msvs-version-not-set-from-c

**Comment by iakanoe** [comment]
After lots of digging, I found that `gRPC` has problems installing with certain versions of NPM in general and it is a dependency for `firebase@^6.0.0`. Is there a way you could update this project to firebase plugin version 7? It would probably also help it be added by the Ionic team to Capacitor... I will try and make it on a PR but I'm not certain if I will be able to do it since I don't know a lot about this.

**Comment by diegodlh** [comment]
If possible, using node <13 seems to solve the problem

**Comment by CFT-Chris** [comment]
Thanks for the digging!  This plugin is planned to be merged with the [fcm](https://github.com/capacitor-community/fcm) plugin in time for Capacitor 3.0, which I will work on making compatible with the latest Firebase library and later versions of Node.
